[package]
name = "taiga_halo2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
sha2 = "0.10.1"
blake2 = "0.9"
lazy_static = "1"
derivative = { version = "2", features = ["use_core"] }
thiserror = "1"
blake2b_simd = "1"
rand_core = {version = "0.6", default-features=false, features = ["getrandom"] }

# halo2
pasta_curves = "0.4"
ff = "0.12"
group = "0.12"
halo2_gadgets = {version = "0.2", features = ["test-dependencies"]}
halo2_proofs = "0.2"
bitvec = "1"
